#############################################################################
# Makefile for building: libsharp.so.1.0.0
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  SHARP.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile SHARP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSING_COMMANDPUB2 -DPLUGIN_VERSION=\"0.0.1\" -DPLUGIN_NAME=\"Demo\" -DGUI_PLUGIN_WIDGET_LIBRARY -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../common -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I../../../bin/plugins/sharp/.moc -isystem /usr/include/libdrm -I../../../bin/plugins/sharp/.ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sharp1.0.0
DISTDIR = /home/achala/SHARP/isera2base_1.8.4-3/command_centre/bin/plugins/sharp/.obj/sharp1.0.0
LINK          = g++
LFLAGS        = -shared -Wl,-soname,libsharp.so.1
LIBS          = $(SUBLIBS) -lpaho-mqttpp3 -lpaho-mqtt3as -lyaml-cpp -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../../../bin/plugins/sharp/.obj/

####### Files

SOURCES       = plugin_template.cpp \
		gui_plugin_widget_export.cpp \
		../../common/gui/common_utils.cpp \
		../../common/gui/websocketdata.cpp \
		../../common/mission/basedata.cpp \
		../../common/mission/mission_completed_data.cpp \
		command_processor/commandprocessor.cpp \
		Tools/console.cpp \
		Tools/robotCommunication.cpp \
		../../common/mission/statuspub2_system_status_data.cpp \
		../../common/mission/tasks_status_data.cpp \
		../../common/mission/robot_status_data2.cpp \
		../../common/mission/mission_data2.cpp \
		../../common/mission/submission_data2.cpp ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp \
		../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp \
		../../../bin/plugins/sharp/.moc/moc_basewidget.cpp \
		../../../bin/plugins/sharp/.moc/moc_console.cpp \
		../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp
OBJECTS       = ../../../bin/plugins/sharp/.obj/plugin_template.o \
		../../../bin/plugins/sharp/.obj/gui_plugin_widget_export.o \
		../../../bin/plugins/sharp/.obj/common_utils.o \
		../../../bin/plugins/sharp/.obj/websocketdata.o \
		../../../bin/plugins/sharp/.obj/basedata.o \
		../../../bin/plugins/sharp/.obj/mission_completed_data.o \
		../../../bin/plugins/sharp/.obj/commandprocessor.o \
		../../../bin/plugins/sharp/.obj/console.o \
		../../../bin/plugins/sharp/.obj/robotCommunication.o \
		../../../bin/plugins/sharp/.obj/statuspub2_system_status_data.o \
		../../../bin/plugins/sharp/.obj/tasks_status_data.o \
		../../../bin/plugins/sharp/.obj/robot_status_data2.o \
		../../../bin/plugins/sharp/.obj/mission_data2.o \
		../../../bin/plugins/sharp/.obj/submission_data2.o \
		../../../bin/plugins/sharp/.obj/qrc_plugin_resources.o \
		../../../bin/plugins/sharp/.obj/moc_plugin_template.o \
		../../../bin/plugins/sharp/.obj/moc_basewidget.o \
		../../../bin/plugins/sharp/.obj/moc_console.o \
		../../../bin/plugins/sharp/.obj/moc_robotCommunication.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SHARP.pro plugin_template.h \
		gui_plugin_widget_export.h \
		gui_plugin_widget_global.h \
		../common/basewidget.h \
		../../common/gui/common_utils.h \
		../../common/gui/websocketdata.h \
		../../common/mission/basedata.h \
		../../common/mission/mission_completed_data.h \
		../../common/fsm_defs.h \
		command_processor/commandprocessor.h \
		Tools/console.h \
		Tools/robotCommunication.h \
		../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/tasks_status_data.h \
		../../common/mission/robot_status_data2.h \
		../../common/mission/mission_data2.h \
		../../common/mission/submission_data2.h plugin_template.cpp \
		gui_plugin_widget_export.cpp \
		../../common/gui/common_utils.cpp \
		../../common/gui/websocketdata.cpp \
		../../common/mission/basedata.cpp \
		../../common/mission/mission_completed_data.cpp \
		command_processor/commandprocessor.cpp \
		Tools/console.cpp \
		Tools/robotCommunication.cpp \
		../../common/mission/statuspub2_system_status_data.cpp \
		../../common/mission/tasks_status_data.cpp \
		../../common/mission/robot_status_data2.cpp \
		../../common/mission/mission_data2.cpp \
		../../common/mission/submission_data2.cpp
QMAKE_TARGET  = sharp
DESTDIR       = ../../../bin/plugins/sharp/
TARGET        = libsharp.so.1.0.0
TARGETA       = ../../../bin/plugins/sharp/libsharp.a
TARGET0       = libsharp.so
TARGETD       = libsharp.so.1.0.0
TARGET1       = libsharp.so.1
TARGET2       = libsharp.so.1.0


first: all
####### Build rules

../../../bin/plugins/sharp/$(TARGET): ../../../bin/plugins/sharp/.ui/ui_plugin_template.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../../bin/plugins/sharp/ || mkdir -p ../../../bin/plugins/sharp/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET)
	-$(MOVE) $(TARGET)  ../../../bin/plugins/sharp/ 
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET0)
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET1)
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET2)
	-$(MOVE) $(TARGET0) ../../../bin/plugins/sharp/ 
	-$(MOVE) $(TARGET1) ../../../bin/plugins/sharp/ 
	-$(MOVE) $(TARGET2) ../../../bin/plugins/sharp/ 



staticlib: $(TARGETA)

$(TARGETA): ../../../bin/plugins/sharp/.ui/ui_plugin_template.h $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: SHARP.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SHARP.pro \
		plugin_resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile SHARP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SHARP.pro:
plugin_resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SHARP.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ../../../bin/plugins/sharp/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents plugin_resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents plugin_template.h gui_plugin_widget_export.h gui_plugin_widget_global.h ../common/basewidget.h ../../common/gui/common_utils.h ../../common/gui/websocketdata.h ../../common/mission/basedata.h ../../common/mission/mission_completed_data.h ../../common/fsm_defs.h command_processor/commandprocessor.h Tools/console.h Tools/robotCommunication.h ../../common/mission/statuspub2_system_status_data.h ../../common/mission/tasks_status_data.h ../../common/mission/robot_status_data2.h ../../common/mission/mission_data2.h ../../common/mission/submission_data2.h $(DISTDIR)/
	$(COPY_FILE) --parents plugin_template.cpp gui_plugin_widget_export.cpp ../../common/gui/common_utils.cpp ../../common/gui/websocketdata.cpp ../../common/mission/basedata.cpp ../../common/mission/mission_completed_data.cpp command_processor/commandprocessor.cpp Tools/console.cpp Tools/robotCommunication.cpp ../../common/mission/statuspub2_system_status_data.cpp ../../common/mission/tasks_status_data.cpp ../../common/mission/robot_status_data2.cpp ../../common/mission/mission_data2.cpp ../../common/mission/submission_data2.cpp $(DISTDIR)/
	$(COPY_FILE) --parents plugin_template.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET) 
	-$(DEL_FILE) ../../../bin/plugins/sharp/$(TARGET0) ../../../bin/plugins/sharp/$(TARGET1) ../../../bin/plugins/sharp/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp
../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp: plugin_resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/sutd-logo-academics.jpg
	/usr/lib/qt5/bin/rcc -name plugin_resources plugin_resources.qrc -o ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp

compiler_moc_predefs_make_all: ../../../bin/plugins/sharp/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) ../../../bin/plugins/sharp/.moc/moc_predefs.h
../../../bin/plugins/sharp/.moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o ../../../bin/plugins/sharp/.moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: ../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp ../../../bin/plugins/sharp/.moc/moc_basewidget.cpp ../../../bin/plugins/sharp/.moc/moc_console.cpp ../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp ../../../bin/plugins/sharp/.moc/moc_basewidget.cpp ../../../bin/plugins/sharp/.moc/moc_console.cpp ../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp
../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp: ../../common/mission/mission_completed_data.h \
		../../common/mission/basedata.h \
		Tools/console.h \
		command_processor/commandprocessor.h \
		Tools/robotCommunication.h \
		../../common/fsm_defs.h \
		../../common/mission/robot_status_data2.h \
		../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/tasks_status_data.h \
		../../common/mission/mission_data2.h \
		../../common/mission/submission_data2.h \
		../../common/mission/robot_status_data.h \
		../../common/mission/statuspubdata.h \
		plugin_template.h \
		../../../bin/plugins/sharp/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ../../../bin/plugins/sharp/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/SHARP -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include plugin_template.h -o ../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp

../../../bin/plugins/sharp/.moc/moc_basewidget.cpp: ../common/gui_common_defs.hpp \
		../common/basewidget.h \
		../../../bin/plugins/sharp/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ../../../bin/plugins/sharp/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/SHARP -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../common/basewidget.h -o ../../../bin/plugins/sharp/.moc/moc_basewidget.cpp

../../../bin/plugins/sharp/.moc/moc_console.cpp: Tools/console.h \
		../../../bin/plugins/sharp/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ../../../bin/plugins/sharp/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/SHARP -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tools/console.h -o ../../../bin/plugins/sharp/.moc/moc_console.cpp

../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp: Tools/console.h \
		Tools/robotCommunication.h \
		../../../bin/plugins/sharp/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ../../../bin/plugins/sharp/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/SHARP -I/home/achala/SHARP/isera2base_1.8.4-3/command_centre/src/command_centre_gui_plugin/common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tools/robotCommunication.h -o ../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ../../../bin/plugins/sharp/.ui/ui_plugin_template.h
compiler_uic_clean:
	-$(DEL_FILE) ../../../bin/plugins/sharp/.ui/ui_plugin_template.h
../../../bin/plugins/sharp/.ui/ui_plugin_template.h: plugin_template.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic plugin_template.ui -o ../../../bin/plugins/sharp/.ui/ui_plugin_template.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

../../../bin/plugins/sharp/.obj/plugin_template.o: plugin_template.cpp plugin_template.h \
		../../common/mission/mission_completed_data.h \
		../../common/mission/basedata.h \
		Tools/console.h \
		command_processor/commandprocessor.h \
		Tools/robotCommunication.h \
		../../common/fsm_defs.h \
		../../common/mission/robot_status_data2.h \
		../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/tasks_status_data.h \
		../../common/mission/mission_data2.h \
		../../common/mission/submission_data2.h \
		../../common/mission/robot_status_data.h \
		../../common/mission/statuspubdata.h \
		../../../bin/plugins/sharp/.ui/ui_plugin_template.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/plugin_template.o plugin_template.cpp

../../../bin/plugins/sharp/.obj/gui_plugin_widget_export.o: gui_plugin_widget_export.cpp gui_plugin_widget_export.h \
		gui_plugin_widget_global.h \
		plugin_template.h \
		../../common/mission/mission_completed_data.h \
		../../common/mission/basedata.h \
		Tools/console.h \
		command_processor/commandprocessor.h \
		Tools/robotCommunication.h \
		../../common/fsm_defs.h \
		../../common/mission/robot_status_data2.h \
		../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/tasks_status_data.h \
		../../common/mission/mission_data2.h \
		../../common/mission/submission_data2.h \
		../../common/mission/robot_status_data.h \
		../../common/mission/statuspubdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/gui_plugin_widget_export.o gui_plugin_widget_export.cpp

../../../bin/plugins/sharp/.obj/common_utils.o: ../../common/gui/common_utils.cpp ../../common/gui/common_utils.h \
		../../common/fsm_defs.h \
		../../common/gui/websocketdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/common_utils.o ../../common/gui/common_utils.cpp

../../../bin/plugins/sharp/.obj/websocketdata.o: ../../common/gui/websocketdata.cpp ../../common/gui/websocketdata.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/websocketdata.o ../../common/gui/websocketdata.cpp

../../../bin/plugins/sharp/.obj/basedata.o: ../../common/mission/basedata.cpp ../../common/mission/basedata.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/basedata.o ../../common/mission/basedata.cpp

../../../bin/plugins/sharp/.obj/mission_completed_data.o: ../../common/mission/mission_completed_data.cpp ../../common/mission/mission_completed_data.h \
		../../common/mission/basedata.h \
		../../common/fsm_defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/mission_completed_data.o ../../common/mission/mission_completed_data.cpp

../../../bin/plugins/sharp/.obj/commandprocessor.o: command_processor/commandprocessor.cpp command_processor/commandprocessor.h \
		Tools/console.h \
		Tools/robotCommunication.h \
		../../common/fsm_defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/commandprocessor.o command_processor/commandprocessor.cpp

../../../bin/plugins/sharp/.obj/console.o: Tools/console.cpp Tools/console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/console.o Tools/console.cpp

../../../bin/plugins/sharp/.obj/robotCommunication.o: Tools/robotCommunication.cpp Tools/robotCommunication.h \
		Tools/console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/robotCommunication.o Tools/robotCommunication.cpp

../../../bin/plugins/sharp/.obj/statuspub2_system_status_data.o: ../../common/mission/statuspub2_system_status_data.cpp ../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/basedata.h \
		../../common/fsm_defs.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h \
		../../common/mission/tasks_status_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/statuspub2_system_status_data.o ../../common/mission/statuspub2_system_status_data.cpp

../../../bin/plugins/sharp/.obj/tasks_status_data.o: ../../common/mission/tasks_status_data.cpp ../../common/mission/tasks_status_data.h \
		../../common/mission/basedata.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h \
		../../common/fsm_defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/tasks_status_data.o ../../common/mission/tasks_status_data.cpp

../../../bin/plugins/sharp/.obj/robot_status_data2.o: ../../common/mission/robot_status_data2.cpp ../../common/mission/robot_status_data2.h \
		../../common/mission/statuspub2_system_status_data.h \
		../../common/mission/basedata.h \
		../../common/mission/tasks_status_data.h \
		../../common/fsm_defs.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/robot_status_data2.o ../../common/mission/robot_status_data2.cpp

../../../bin/plugins/sharp/.obj/mission_data2.o: ../../common/mission/mission_data2.cpp ../../common/mission/mission_data2.h \
		../../common/mission/basedata.h \
		../../common/mission/submission_data2.h \
		../../common/fsm_defs.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/mission_data2.o ../../common/mission/mission_data2.cpp

../../../bin/plugins/sharp/.obj/submission_data2.o: ../../common/mission/submission_data2.cpp ../../common/mission/submission_data2.h \
		../../common/mission/basedata.h \
		../../common/fsm_defs.h \
		../../common/logger.hpp \
		../../common/logger4cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/submission_data2.o ../../common/mission/submission_data2.cpp

../../../bin/plugins/sharp/.obj/qrc_plugin_resources.o: ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/qrc_plugin_resources.o ../../../bin/plugins/sharp/.qrc/qrc_plugin_resources.cpp

../../../bin/plugins/sharp/.obj/moc_plugin_template.o: ../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/moc_plugin_template.o ../../../bin/plugins/sharp/.moc/moc_plugin_template.cpp

../../../bin/plugins/sharp/.obj/moc_basewidget.o: ../../../bin/plugins/sharp/.moc/moc_basewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/moc_basewidget.o ../../../bin/plugins/sharp/.moc/moc_basewidget.cpp

../../../bin/plugins/sharp/.obj/moc_console.o: ../../../bin/plugins/sharp/.moc/moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/moc_console.o ../../../bin/plugins/sharp/.moc/moc_console.cpp

../../../bin/plugins/sharp/.obj/moc_robotCommunication.o: ../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../../bin/plugins/sharp/.obj/moc_robotCommunication.o ../../../bin/plugins/sharp/.moc/moc_robotCommunication.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

